### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by botandrose**

### CODE REVIEW

**Comment by botandrose** [comment]
Okay, @JakeTheSnake3p0, I've taken a good look at your code. Good work! The tests were nice and green. Looking at the implementation, I think that reliance on `which` and `where` and other OS-specific knowledge was adding too much complexity, so I found a nice cross-platform where implementation (thanks @mislav), and swapped that in.

Would you do me a favor and check out this branch and see if the tests all pass on your Windows machine? If so, then I'll merge this and release!

**Comment by JakeTheSnake3p0** [comment]
I'm not worrying about it at the moment, but I got a bundler warning in my Ubuntu dev box:

```
sprockets-image_compressor at /home/jake/.rvm/gems/ruby-2.1.0@manager/bundler/gems/sprockets-image_compressor-d89925271a4c did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  duplicate dependency on rake (>= 0, development), (>= 0) use:
    add_runtime_dependency 'rake', '>= 0', '>= 0'
```

**Comment by JakeTheSnake3p0** [comment]
I think there's an issue outside of this gem that's causing yet another error. I kept getting 'PNG compression failed...' errors so I went into IRB and tried manually calling the methods to see what was up.

```
c = Sprockets::ImageCompressor::PngCompressor.new
c.binary_path # returns the correct executable, and after manually calling it using system() call, I know it works
c.compress File.binread("[some-file-location]") # it worked.
```

I think Sprockets isn't sending all the binary data to this gem, only the 5 byte header. Running `bundle exec rake assets:precompile` gives me the errors again. I copied the gem locally and `puts content.inspect` and it was just the headers. So I'd say as far as this gem is concerned, it's a "success"!

**Comment by botandrose** [comment]
Interesting. So the tests are passing on your machine, but in practice, some pngs aren't working? Is it some pngs or all?

**Comment by JakeTheSnake3p0** [comment]
All PNGs...JPEGs are fine. I've submitted an [issue](https://github.com/sstephenson/sprockets/issues/640#issuecomment-55978264) on the subject.

**Comment by botandrose** [comment]
Released v0.3.0!

**Pull request merged**
