### PR TITLE
Allow for finding system binaries on Windows systems as well

### PR DESCRIPTION
**Pull request by JakeTheSnake3p0**
sprockets-image_compressor vaguely fails when precompiling, but makes no mention of why. I tracked down my problem to the fact that the executable was "found", but still inaccessible - which meant that the output file was never created. The gem now looks to see if the executable file actually exists.

### CODE REVIEW

**Comment by botandrose** [comment]
Thanks for looking into this @JakeTheSnake3p0 ! Looks like we have a test failure, though... can you take a look? The first commit looks good, though.

**Comment by JakeTheSnake3p0** [comment]
I should have some time to look at it tonight. I've been getting closer and closer to figuring out my original problem and it has to do with cygwin. This gem uses `which`, which returns a cygwin path in my environment. However every system call uses Windows' cmd and not bash, so the execution of pngcrush fails. I'm looking into installing pngcrush/jpegoptim within cygwin to see if that solves it. If that doesn't, I may try to modify the gem somehow.

**Comment by botandrose** [comment]
Interesting. I have no experience with dealing with Windows' quirks, so sorry I can't be much help here. :\

**Comment by JakeTheSnake3p0** [comment]
I've updated it a bit more tonight, but I tried discerning your tests and I don't quite understand the logic. I've only recently begun testing and I'm not comprehending the meaning of `should_receive` for example. On a cursory view it looks like you're testing the process of the method and not the end result.

I've got it to the point where it executes the system file just fine, but I'm having yet another issue where sprockets is sending the first few header bytes into the image compressor but nothing else. I don't know how to troubleshoot that. I seriously wish I had another Ubuntu-only box :\

**Comment by botandrose** [comment]
The idea behind `should_receive` is to stub out a dependency, which in this case is the interface to the filesystem via Kernel#` and Kernel#system. The test is basically saying: assuming that we get so-and-so response from the call to "which pngcrush", then such-and-such things should happen. It does couple the tests to the implementation, though, and if I were to rewrite these tests today, I'd probably write them a bit differently. :\

**Comment by botandrose** [comment]
So I think the right thing to do here is to extract out the binary finding into a new object, `BinaryFinder` or something. Then we can set it up to swap out that finder with a `WindowsBinaryFinder` that implements the same thing on the Windows platform. I'm not quite sure how we can reliably test this, though, considering Travis doesn't support Windows, yet.

**Comment by JakeTheSnake3p0** [comment]
If we're stubbing out system responses then I don't think it'll be a problem as far as tests go. I won't have time to work on this until next week however.

**Comment by JakeTheSnake3p0** [comment]
I had to rewrite the test suites; both the jpg_compressor_spec and png_compressor_spec suites contained duplicate tests of one another, just with different file names. I put those tests in the binary_finder_spec suite.  I also updated the rspec syntax from `should` to `expect` on all test suites.

FWIW, I haven't run this latest revision on my Windows machine but I don't expect issues. I should be able to test (live) some time tomorrow or Friday. It precompiled assets just fine on my Ubuntu VM.

**Comment by JakeTheSnake3p0** [comment]
Have you had a chance to look at the update?

**Comment by botandrose** [comment]
I haven't yet! Sorry for the slowness. A lot of changes here and I want to make sure I give it a solid review. I'll see if I can't squeeze in some time today.

**Comment by botandrose** [comment]
Quickly, though, it looks like this branch has some merge conflicts with master, so can you rebase on master and force push? You can squash some of those commits together while you're at it, too.

**Comment by JakeTheSnake3p0** [comment]
I'm afraid I'm quite unsure of myself when it comes to git, and I don't know if I've done exactly what you wanted as far as squashing/rebasing. I'm using SourceTree FWIW. I've tried an interactive rebase and I merged all of my changes into a single commit, but as far as the SourceTree interface is concerned I can still see all of my prior commits. I also then tried rebasing with your branch but I'll be damned if I can tell if anything happened. :S

**Comment by botandrose** [comment]
Hmm, yes there are still merge conflicts, so the rebase didn't quite take. I'm not familiar with SourceTree, so I can't help there, sorry. I'll check this branch out and see what I can do. Thanks for your work on this!

**Comment by botandrose** [comment]
Okay, see #20

**Pull request closed without merging**
