### PR TITLE
fix(PngCompressor): for #12

### LINKED ISSUE #12: sporadic precompile failures on heroku
I'm getting sporadic failures precompiling on heroku with this gem.  You can see one below.  Anyone else seen this?  Is it some sort of filesystem issue on heroku?

```
   I, [2014-03-06T22:27:31.214690 #888]  INFO -- : Writing /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/public/assets/icons/right-arrow-f4b92e0eb8fb3b6d72e85e8ff14f7a42.png
   rake aborted!
   No such file or directory @ rb_sysopen - /tmp/in_file20140306-888-n5rzjl.png.optimized.png
   (in /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/app/assets/images/icons/star-no.png)
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:20:in `initialize'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:20:in `open'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:20:in `block in compress'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/png_compressor.rb:12:in `compress'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-image_compressor-0.2.2/lib/sprockets/image_compressor/integration.rb:9:in `block in setup'
   /tmp/build_e464bac0-fcbd-4cd0-b563-7749bbc2af6d/vendor/bundle/ruby/2.1.0/gems/sprockets-2.10.1/lib/sprockets/processor.rb:29:in `call'
```

### PR DESCRIPTION
**Pull request by tomchentw**
This will fix #12.
I'm facing the same issue and I found this is png image error. In my case, it's [admin_notes_icon](https://github.com/gregbell/active_admin/blob/master/app/assets/images/active_admin/admin_notes_icon.png).
I tried to compile that file using cli and it will error, so here's a quick fix.
- don't delete in_file
- catch exception during compression

### CODE REVIEW

**Comment by botandrose** [comment]
I see, so the idea is to fallback to the uncompressed version if something goes wrong during compression? Looks good, but I think rescuing Exception is too general. Can we rescue a more specific exception?

**Comment by tomchentw** [comment]
@botandrose updated! Only catch `Errno::ENOENT` now.

**Comment by botandrose** [comment]
Merged. Thanks!

**Comment by botandrose** [comment]
Released v0.2.3.

**Comment by tomchentw** [comment]
Cool! Thanks!!

**Pull request merged**
